/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.Controller;
import DTO.DTOVisitas;
import Modelo.Visitas;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NotebookSFC
 */
public class frmListado extends javax.swing.JFrame {
        private frmAlta ventanaAlta;
        private frmReporte ventanaReporte;
    /**
     * Creates new form frmListado
     */
    public frmListado() {
        initComponents();
        cargarTabla();
    }
    
    public void cargarTabla()
    {
        Controller gestor = new Controller();
        ArrayList<DTOVisitas> visita = gestor.obtenerVisitasDTO();
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.setColumnIdentifiers(new Object[] {"Paciente", "Visitante", "Recepcionista", "Duracion"});
        
        for (DTOVisitas dTOVisitas : visita) 
        {
            tabla.addRow(new Object [] {dTOVisitas.getPaciente(), dTOVisitas.getVisitante(), dTOVisitas.getRecepcionista(), dTOVisitas.getDuracion()});
        }
        tblListado.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        btnvoleralta = new javax.swing.JButton();
        btnirreportes = new javax.swing.JButton();
        btnvoleralta1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setText("Listado de Pacientes por Visita");

        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblListado);

        btnvoleralta.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnvoleralta.setText("Volver a Alta");
        btnvoleralta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoleraltaActionPerformed(evt);
            }
        });

        btnirreportes.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnirreportes.setText("Ir a Reportes");
        btnirreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnirreportesActionPerformed(evt);
            }
        });

        btnvoleralta1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnvoleralta1.setText("Salir");
        btnvoleralta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoleralta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnvoleralta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnirreportes)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnvoleralta1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnvoleralta1)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnvoleralta)
                            .addComponent(btnirreportes))
                        .addGap(69, 69, 69))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvoleraltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoleraltaActionPerformed
        if(ventanaAlta == null){
            ventanaAlta = new frmAlta();
            ventanaAlta.setVisible(true);
        }

    }//GEN-LAST:event_btnvoleraltaActionPerformed

    private void btnirreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnirreportesActionPerformed
      if(ventanaReporte == null){
            ventanaReporte = new frmReporte();
      }
            ventanaReporte.setVisible(true);
    }//GEN-LAST:event_btnirreportesActionPerformed

    private void btnvoleralta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoleralta1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnvoleralta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnirreportes;
    private javax.swing.JButton btnvoleralta;
    private javax.swing.JButton btnvoleralta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblListado;
    // End of variables declaration//GEN-END:variables
}
