/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instrumentos;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author NotebookSFC
 */
public class Principal extends javax.swing.JFrame {
    private Arreglos A;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        A = new Arreglos();
        btnreportes.setEnabled(true);
        rbtviento.setSelected(true);
        txtcantcuerdas.setEnabled(false);
        
    }
    
    public boolean validation()
    {
        if(txtnombrecliente.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "El Nombre del Cliente debe agregarse");
            txtnombrecliente.requestFocus();
            return false;
        }
        
        if(txtnombreinstrumento.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "El Nombre del Instrumento debe agregarse");
            txtnombreinstrumento.requestFocus();
            return false;
        }
        
        if(txtcantsemanas.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "La cantidad de semanas debe agregarse");
            txtcantsemanas.requestFocus();
            return false;
        }
        if(rbtcuerda.isSelected())
        {
            if(txtcantcuerdas.getText().isEmpty())
            {
            JOptionPane.showMessageDialog(null, "La cantidad de cuerdas debe agregarse");
            txtcantcuerdas.requestFocus();
            return false;
            }                
        }       
        return true;
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnaceptar = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        rbtviento = new javax.swing.JRadioButton();
        rbtcuerda = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstclientes = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        txttotalrecaudadocuerdas = new javax.swing.JTextField();
        txtnombrecliente = new javax.swing.JTextField();
        txtnombreinstrumento = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtmayorduracion = new javax.swing.JTextField();
        txtsindesinfeccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcantsemanas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtcantcuerdas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Total recaudado de instrumentos de cuerda: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel2.setText("Nombre del cliente con mayor duración: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel3.setText("Nombre de Instrumento: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setText("Precio: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel5.setText("ALQUILERES DE INSTRUMENTOS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel6.setText("Tipo de Instrumento: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btnaceptar.setText("Aceptar");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        btnreportes.setText("Reportes");
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        buttonGroup1.add(rbtviento);
        rbtviento.setText("Viento");
        rbtviento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtvientoActionPerformed(evt);
            }
        });
        getContentPane().add(rbtviento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        buttonGroup1.add(rbtcuerda);
        rbtcuerda.setText("Cuerda");
        rbtcuerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtcuerdaActionPerformed(evt);
            }
        });
        getContentPane().add(rbtcuerda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel7.setText("Total Ganado sin gastos desinfección: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jScrollPane1.setViewportView(lstclientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 500, 360));

        jLabel8.setText("Nombre del Cliente: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        getContentPane().add(txttotalrecaudadocuerdas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 120, -1));

        txtnombrecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreclienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombrecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, -1));
        getContentPane().add(txtnombreinstrumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 120, -1));
        getContentPane().add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 120, -1));
        getContentPane().add(txtmayorduracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 120, -1));
        getContentPane().add(txtsindesinfeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 120, -1));

        jLabel9.setText("Listado de Clientes");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel10.setText("Cantidad de Semanas: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtcantsemanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantsemanasActionPerformed(evt);
            }
        });
        getContentPane().add(txtcantsemanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, -1));

        jLabel11.setText("Cantidad de Cuerdas: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtcantcuerdas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantcuerdasActionPerformed(evt);
            }
        });
        getContentPane().add(txtcantcuerdas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        if(validation()) 
        {
        String nombreCliente = txtnombrecliente.getText();
        String nombreInstrumento = txtnombreinstrumento.getText();
        int cantSemanas = Integer.parseInt(txtcantsemanas.getText());
        
        if(rbtviento.isSelected())
        {
            IViento iv = new IViento(nombreCliente, nombreInstrumento, cantSemanas, PROPERTIES);
            A.agregarAlquiler(iv);
        }
        else
        {
            int cantCuerdas = Integer.parseInt(txtcantcuerdas.getText());
            ICuerda ic = new ICuerda(nombreCliente, nombreInstrumento, cantSemanas, cantCuerdas);
            A.agregarAlquiler(ic);
        }
        
        lstclientes.setListData(A.getAlquileres().toArray()); //agrego el listado al list
        JOptionPane.showMessageDialog(this,"Alquiler registrado con éxito!");        
        txtnombrecliente.setText("");
        txtnombreinstrumento.setText("");
        txtcantcuerdas.setText("");
        txtcantsemanas.setText("");
        btnreportes.setEnabled(true);          
        }      
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void rbtvientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtvientoActionPerformed
        txtcantcuerdas.setEnabled(false);
    }//GEN-LAST:event_rbtvientoActionPerformed

    private void rbtcuerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtcuerdaActionPerformed
        txtcantcuerdas.setEnabled(true);
    }//GEN-LAST:event_rbtcuerdaActionPerformed

    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
        txtmayorduracion.setText(String.valueOf(A.ClienteMayorDuracion()));
        txtsindesinfeccion.setText(String.valueOf(A.TotalGanadoSinDesinfeccion()));
        txttotalrecaudadocuerdas.setText(String.valueOf(A.TotalRecaudadoInstrumentoCuerda()));

    }//GEN-LAST:event_btnreportesActionPerformed

    private void txtcantsemanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantsemanasActionPerformed
        String text = txtcantsemanas.getText(); //validaciones solo numeros
        try {
            int x = Integer.parseInt(text);
            }
         catch (NumberFormatException nfe) 
        {
            JOptionPane.showMessageDialog(null, "Sólo números");
        }
    }//GEN-LAST:event_txtcantsemanasActionPerformed

    private void txtcantcuerdasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantcuerdasActionPerformed
        String text =  txtcantcuerdas.getText();
        try {
            int x = Integer.parseInt(text);
            }
         catch (NumberFormatException nfe) 
        {
            JOptionPane.showMessageDialog(null, "Sólo números");
        }
    }//GEN-LAST:event_txtcantcuerdasActionPerformed

    private void txtnombreclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreclienteActionPerformed
              
    }//GEN-LAST:event_txtnombreclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btnreportes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstclientes;
    private javax.swing.JRadioButton rbtcuerda;
    private javax.swing.JRadioButton rbtviento;
    private javax.swing.JTextField txtcantcuerdas;
    private javax.swing.JTextField txtcantsemanas;
    private javax.swing.JTextField txtmayorduracion;
    private javax.swing.JTextField txtnombrecliente;
    private javax.swing.JTextField txtnombreinstrumento;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtsindesinfeccion;
    private javax.swing.JTextField txttotalrecaudadocuerdas;
    // End of variables declaration//GEN-END:variables
}
